image: node:12.13.1

pipelines:
  branches:
    master:
      - step:
          name: Tests
          caches:
            - node
          script:
            - npm install
            - npm test
      - step:
          name: Build
          caches:
            - node
          script:
            - npm install
            - npm run srv-dist
            - npm run client-dist
            - npm run create-archive
          artifacts:
            - "bluetetris.tar.gz"
      - step:
          name: Deploy to production
          deployment: production
          script:
            - pipe: atlassian/heroku-deploy:1.1.4
              variables:
                HEROKU_API_KEY: $HEROKU_API_KEY
                HEROKU_APP_NAME: $HEROKU_APP_NAME
                ZIP_FILE: "bluetetris.tar.gz"
                WAIT: "true"
                DEBUG: "false"
