image: node:12.13.1

clone:
  depth: full

pipelines:
  branches:
    master:
      - step:
          name: Tests
          caches:
            - node
          script:
            - npm install
            - npm test
          services:
            - mongo
      - step:
          name: Build
          caches:
            - node
          script:
            - npm install
            - npm run srv-dist
            - npm run client-dist
      - step:
          name: Deploy to production
          deployment: production
          script:
            - git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD
definitions:
  services:
    mongo:
      image: mongo:4.2
