version: "3.1"

services:
  mongo:
    container_name: mongodb
    image: mongo:4.2
    restart: always
    ports:
      - 27017-27019:27017-27019

  mongo-express:
    container_name: mongo-express
    image: mongo-express:0.49
    restart: always
    ports:
      - 8081:8081
