version: '3.1'

services:
  mongo:
    image: mongo:4.2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: red
      MONGO_INITDB_ROOT_PASSWORD: tetris

  mongo-express:
    image: mongo-express:0.49
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: red
      ME_CONFIG_MONGODB_ADMINPASSWORD: tetris